#HomePage
LoginLink=//a[text()='Log in']
Logout=//a[text()='Log out']
Username=//input[@id='loginusername']
Password=//input[@id='loginpassword']
LoginButton=//button[text()='Log in']
UndereriterUsername=Underwriter
SelectProduct=//a[text()='Samsung galaxy s6']
LoginValidation=//*[contains(text(),'Welcome')]
Cart=//a[text()='Cart']
#HomePage

#Cart
AddToCart=//a[text()='Add to cart']
CartValidate=//td[text()='Samsung galaxy s6']
#Cart

#Place Order
PlaceOrder=//button[text()='Place Order']
Name=//input[@id='name']
Country=//input[@id='country']
City=//input[@id='city']
CreditCard=//input[@id='card']
Month=//input[@id='month']
Year=//input[@id='year']
Purchase=//button[text()='Purchase']
PurchaseConfirmation=//h2[text()='Thank you for your purchase!']
ReturnToHome=//button[text()='OK']

#Place Order
